name: Update Commits Data

on:
  push:
    branches: [ main ]
    # 排除更新 commits.json 的提交，避免無限循環
    paths-ignore:
      - 'assets/js/commits.json'
      - 'assets/js/languages.json'
  workflow_dispatch:
    inputs:
      show_all_commits:
        description: 'Show all commits (including automation commits)'
        required: false
        default: 'false'
        type: choice
        options:
        - 'true'
        - 'false'
      max_commits:
        description: 'Maximum number of commits to include'
        required: false
        default: '100'

jobs:
  update-commits:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Generate commits data
      run: |
        if [ "${{ github.event.inputs.show_all_commits }}" = "true" ]; then
          pwsh -File scripts/generate-commits.ps1 -MaxCommits ${{ github.event.inputs.max_commits || '100' }} -ShowAll
        else
          pwsh -File scripts/generate-commits.ps1 -MaxCommits ${{ github.event.inputs.max_commits || '100' }}
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain assets/js/commits.json)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add assets/js/commits.json
        git commit -m "chore(ci): update commits.json [skip ci]"
        git push